name: github pages

on: [push]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm ci
    - run: npm run docs:build

    - name: Deploy agritheory.github.io/forten
      uses: peaceiris/actions-gh-pages@v3
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: packages/docs/.vitepress/dist
        publish_branch: gh-pages