name: github pages

on: [push]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm ci
    - run: npm run docs:build

    - name: Deploy agritheory.github.io/forten
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        EXTERNAL_REPOSITORY: forten/agritheory.github.io #Can create a new mybells.github.io warehouse and publish it to the master
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: docs/.vuepress/dist
      with:
          emptyCommits: false